//! Minerva infrastructure layer.
//!
//! Adapters for external systems: Postgres (Diesel), Redis, and
//! S3-compatible object storage (`object_store`). Not yet implemented —
//! scaffolding only. All configuration is read from environment variables.

/// Diesel schema, generated by the CLI into this file (see `diesel.toml`).
pub mod schema;
