//! Minerva infrastructure layer.
//!
//! Adapters for external systems: Postgres (Diesel), Redis,
//! S3-compatible object storage (`object_store`), and an OpenID Connect
//! identity provider. The Postgres adapters live in `db` (connection pooling)
//! and `repositories`; the OIDC adapter lives in `oidc`. All configuration is
//! read from environment variables.

pub mod db;
pub mod email;
pub mod error;
pub mod migrations;
pub mod oidc;
pub mod password_hasher;
pub mod repositories;
pub mod session_tokens;

pub use email::NoEmailSender;
pub use password_hasher::Argon2PasswordHasher;
pub use session_tokens::Sha256SessionTokens;

/// Diesel schema, generated by the CLI into this file (see `diesel.toml`).
pub mod schema;
