//! Minerva infrastructure layer.
//!
//! Adapters for external systems: Postgres (Diesel), Redis,
//! S3-compatible object storage (`object_store`), and an OpenID Connect
//! identity provider. The Postgres adapters live in `db` (connection pooling)
//! and `repositories`; the OIDC adapter lives in `oidc`. All configuration is
//! read from environment variables.

pub mod db;
pub mod error;
pub mod migrations;
pub mod oidc;
pub mod password_hasher;
pub mod repositories;

pub use password_hasher::Argon2PasswordHasher;

/// Diesel schema, generated by the CLI into this file (see `diesel.toml`).
pub mod schema;
