//! Argon2id implementation of [`PasswordHasher`].

use std::sync::OnceLock;

use application::ports::{PasswordHashError, PasswordHasher};
use argon2::password_hash::{PasswordHash, PasswordVerifier, SaltString, rand_core::OsRng};
// The hashing side of the argon2 API; imported anonymously because its name
// collides with the application-layer port trait.
use argon2::Argon2;
use argon2::password_hash::PasswordHasher as _;

/// [`PasswordHasher`] backed by the `argon2` crate.
///
/// Uses `Argon2::default()` — Argon2id with the crate's default cost
/// parameters (19 MiB, 2 iterations), the OWASP-recommended baseline. The
/// CPU-bound work runs on a blocking thread so it cannot stall the async
/// runtime's worker threads.
pub struct Argon2PasswordHasher;

/// The hash of a fixed dummy password, generated once per process with the
/// same `Argon2::default()` parameters as real hashes. The adapter takes no
/// configuration, so one shared value is correct for every instance.
static DUMMY_HASH: OnceLock<String> = OnceLock::new();

fn dummy_hash() -> &'static str {
    DUMMY_HASH.get_or_init(|| {
        let salt = SaltString::generate(&mut OsRng);
        Argon2::default()
            .hash_password(b"minerva-dummy-password", &salt)
            .map(|hashed| hashed.to_string())
            .expect("generating the dummy hash cannot fail")
    })
}

#[async_trait::async_trait]
impl PasswordHasher for Argon2PasswordHasher {
    async fn hash(&self, password: &str) -> Result<String, PasswordHashError> {
        let password = password.to_owned();
        tokio::task::spawn_blocking(move || {
            let salt = SaltString::generate(&mut OsRng);
            Argon2::default()
                .hash_password(password.as_bytes(), &salt)
                .map(|hashed| hashed.to_string())
                .map_err(|err| PasswordHashError::OperationFailed(err.to_string()))
        })
        .await
        .map_err(|err| PasswordHashError::OperationFailed(err.to_string()))?
    }

    async fn verify(&self, password: &str, hash: &str) -> Result<bool, PasswordHashError> {
        let password = password.to_owned();
        let hash = hash.to_owned();
        tokio::task::spawn_blocking(move || {
            let parsed = PasswordHash::new(&hash).map_err(|err| {
                PasswordHashError::OperationFailed(format!("unparseable stored hash: {err}"))
            })?;
            Ok(Argon2::default()
                .verify_password(password.as_bytes(), &parsed)
                .is_ok())
        })
        .await
        .map_err(|err| PasswordHashError::OperationFailed(err.to_string()))?
    }

    async fn verify_dummy(&self, password: &str) -> Result<bool, PasswordHashError> {
        let password = password.to_owned();
        let hash = dummy_hash().to_owned();
        tokio::task::spawn_blocking(move || {
            let parsed =
                PasswordHash::new(&hash).expect("the dummy hash was generated by this adapter");
            // The work is the point: a full Argon2 verification at real cost.
            let _ = Argon2::default().verify_password(password.as_bytes(), &parsed);
        })
        .await
        .map_err(|err| PasswordHashError::OperationFailed(err.to_string()))?;
        Ok(false)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The decimal value of one Argon2 cost parameter (`m`, `t` or `p`) out
    /// of a parsed PHC string.
    fn cost(hash: &PasswordHash<'_>, name: &str) -> u32 {
        hash.params
            .get(name)
            .expect("parameter present")
            .decimal()
            .expect("decimal parameter")
    }

    /// The dummy hash must carry the same Argon2 parameters as a real hash:
    /// parse both PHC strings and compare memory, time and parallelism.
    #[tokio::test]
    async fn dummy_hash_uses_the_same_parameters_as_real_hashes() {
        let hasher = Argon2PasswordHasher;
        let real = hasher.hash("some password").await.expect("hash a password");
        let dummy = dummy_hash().to_owned();
        let real = PasswordHash::new(&real).expect("parse the real hash");
        let dummy = PasswordHash::new(&dummy).expect("parse the dummy hash");
        assert_eq!(cost(&real, "m"), cost(&dummy, "m"));
        assert_eq!(cost(&real, "t"), cost(&dummy, "t"));
        assert_eq!(cost(&real, "p"), cost(&dummy, "p"));
    }
}
